services:
  - type: web
    name: zoom-clone-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromService:
          type: web
          name: zoom-clone-frontend
          property: url
    healthCheckPath: /health
